apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobo
  labels:
    app: bobo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobo
  template:
    metadata:
      labels:
        app: bobo
    spec:
      containers:
      - name: bobo
        image: ghcr.io/braveantony/bobo:33d5d36
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bobo
  annotations:
    # 固定使用 bobo-pool 的 IP，pool 定義在 yaml/infra/cilium-lb-bobo.yaml
    lbipam.cilium.io/ips: 10.89.0.225
spec:
  selector:
    app: bobo
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
